version: '3.9'
services:
  backend:
    build: ./backend
    container_name: slide-reviewer-backend
    env_file:
      - ./backend/.env
    restart: unless-stopped
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: slide-reviewer-frontend
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "5173:80" 